export const customerData = [
  {
    id: "1",
    name: "Amit Sharma",
    email: "amit.sharma@gmail.com",
    phone: "+91 9876543210",
    address: {
      location: "5th Floor, Sunrise Tower",
      city: "Delhi",
      state: "Delhi",
      pin: "110001",
    },
  },
  {
    id: "2",
    name: "Priya Verma",
    email: "priya.verma@hotmail.com",
    phone: "+91 9876543220",
    address: {
      location: "21, New Rajendra Nagar",
      city: "Mumbai",
      state: "Maharashtra",
      pin: "400001",
    },
  },
  {
    id: "3",
    name: "Ravi Patel",
    email: "ravi.patel@yahoo.com",
    phone: "+91 9876543230",
    address: {
      location: "123, Shanti Villa",
      city: "Ahmedabad",
      state: "Gujarat",
      pin: "380001",
    },
  },
  {
    id: "4",
    name: "Sunita Iyer",
    email: "sunita.iyer@gmail.com",
    phone: "+91 9876543240",
    address: {
      location: "C-13, Om Nagar",
      city: "Bangalore",
      state: "Karnataka",
      pin: "560001",
    },
  },
  {
    id: "5",
    name: "Karan Singh",
    email: "karan.singh@outlook.com",
    phone: "+91 9876543250",
    address: {
      location: "Flat 302, Satyam Heights",
      city: "Chennai",
      state: "Tamil Nadu",
      pin: "600001",
    },
  },
  {
    id: "6",
    name: "Neha Reddy",
    email: "neha.reddy@gmail.com",
    phone: "+91 9876543260",
    address: {
      location: "A-25, Shilpa Enclave",
      city: "Hyderabad",
      state: "Telangana",
      pin: "500001",
    },
  },
  {
    id: "7",
    name: "Vikram Joshi",
    email: "vikram.joshi@yahoo.com",
    phone: "+91 9876543270",
    address: {
      location: "F-12, Shivaji Nagar",
      city: "Pune",
      state: "Maharashtra",
      pin: "411001",
    },
  },
  {
    id: "8",
    name: "Anjali Mehta",
    email: "anjali.mehta@outlook.com",
    phone: "+91 9876543280",
    address: {
      location: "B-45, Vikram Vihar",
      city: "Kolkata",
      state: "West Bengal",
      pin: "700001",
    },
  },
  {
    id: "9",
    name: "Ajay Kumar",
    email: "ajay.kumar@yahoo.com",
    phone: "+91 9876543290",
    address: {
      location: "M-13, Kailash Colony",
      city: "Lucknow",
      state: "Uttar Pradesh",
      pin: "226001",
    },
  },
  {
    id: "10",
    name: "Rashmi Sinha",
    email: "rashmi.sinha@gmail.com",
    phone: "+91 9876543300",
    address: {
      location: "G-6, Sector 16",
      city: "Noida",
      state: "Uttar Pradesh",
      pin: "201301",
    },
  },
  {
    id: "11",
    name: "Rohit Gupta",
    email: "rohit.gupta@gmail.com",
    phone: "+91 9876543310",
    address: {
      location: "H-32, Green Park",
      city: "Delhi",
      state: "Delhi",
      pin: "110016",
    },
  },
  {
    id: "12",
    name: "Sonia Chaudhary",
    email: "sonia.chaudhary@hotmail.com",
    phone: "+91 9876543320",
    address: {
      location: "B-20, Rajouri Garden",
      city: "Mumbai",
      state: "Maharashtra",
      pin: "400011",
    },
  },
  {
    id: "13",
    name: "Sandeep Yadav",
    email: "sandeep.yadav@outlook.com",
    phone: "+91 9876543330",
    address: {
      location: "F-8, Anand Nagar",
      city: "Bhopal",
      state: "Madhya Pradesh",
      pin: "462001",
    },
  },
  {
    id: "14",
    name: "Sakshi Chopra",
    email: "sakshi.chopra@gmail.com",
    phone: "+91 9876543340",
    address: {
      location: "C-25, Shivaji Nagar",
      city: "Jaipur",
      state: "Rajasthan",
      pin: "302001",
    },
  },
  {
    id: "15",
    name: "Anil Kumar",
    email: "anil.kumar@ymail.com",
    phone: "+91 9876543350",
    address: {
      location: "E-9, Malviya Nagar",
      city: "Indore",
      state: "Madhya Pradesh",
      pin: "452001",
    },
  },
  {
    id: "16",
    name: "Geeta Patel",
    email: "geeta.patel@gmail.com",
    phone: "+91 9876543360",
    address: {
      location: "A-18, Bhavnagar Colony",
      city: "Surat",
      state: "Gujarat",
      pin: "395001",
    },
  },
  {
    id: "17",
    name: "Prashant Nair",
    email: "prashant.nair@outlook.com",
    phone: "+91 9876543370",
    address: {
      location: "B-7, Koramangala",
      city: "Bangalore",
      state: "Karnataka",
      pin: "560034",
    },
  },
  {
    id: "18",
    name: "Divya Singh",
    email: "divya.singh@gmail.com",
    phone: "+91 9876543380",
    address: {
      location: "M-20, Gokulam",
      city: "Chennai",
      state: "Tamil Nadu",
      pin: "600086",
    },
  },
  {
    id: "19",
    name: "Vishal Shukla",
    email: "vishal.shukla@yahoo.com",
    phone: "+91 9876543390",
    address: {
      location: "J-17, Azad Nagar",
      city: "Kanpur",
      state: "Uttar Pradesh",
      pin: "208001",
    },
  },
  {
    id: "20",
    name: "Madhuri Rao",
    email: "madhuri.rao@gmail.com",
    phone: "+91 9876543400",
    address: {
      location: "N-5, Lalbagh",
      city: "Hyderabad",
      state: "Telangana",
      pin: "500044",
    },
  },
  {
    id: "21",
    name: "Manoj Kothari",
    email: "manoj.kothari@hotmail.com",
    phone: "+91 9876543410",
    address: {
      location: "D-10, Chetak Nagar",
      city: "Jodhpur",
      state: "Rajasthan",
      pin: "342001",
    },
  },
  {
    id: "22",
    name: "Neelam Kaur",
    email: "neelam.kaur@gmail.com",
    phone: "+91 9876543420",
    address: {
      location: "P-16, Model Town",
      city: "Ludhiana",
      state: "Punjab",
      pin: "141001",
    },
  },
  {
    id: "23",
    name: "Arvind Kumar",
    email: "arvind.kumar@yahoo.com",
    phone: "+91 9876543430",
    address: {
      location: "T-5, Gandhi Nagar",
      city: "Patna",
      state: "Bihar",
      pin: "800001",
    },
  },
  {
    id: "24",
    name: "Sneha Sharma",
    email: "sneha.sharma@gmail.com",
    phone: "+91 9876543440",
    address: {
      location: "S-15, Sadar Bazar",
      city: "Agra",
      state: "Uttar Pradesh",
      pin: "282001",
    },
  },
  {
    id: "25",
    name: "Sandeep Singh",
    email: "sandeep.singh@hotmail.com",
    phone: "+91 9876543450",
    address: {
      location: "V-10, Sector 12",
      city: "Gurgaon",
      state: "Haryana",
      pin: "122001",
    },
  },
  {
    id: "26",
    name: "Pooja Gupta",
    email: "pooja.gupta@gmail.com",
    phone: "+91 9876543460",
    address: {
      location: "B-10, Vikram Vihar",
      city: "Faridabad",
      state: "Haryana",
      pin: "121001",
    },
  },
  {
    id: "27",
    name: "Saurabh Mishra",
    email: "saurabh.mishra@ymail.com",
    phone: "+91 9876543470",
    address: {
      location: "H-3, Vikramshila",
      city: "Allahabad",
      state: "Uttar Pradesh",
      pin: "211001",
    },
  },
  {
    id: "28",
    name: "Shubham Yadav",
    email: "shubham.yadav@outlook.com",
    phone: "+91 9876543480",
    address: {
      location: "M-10, Bada Bazar",
      city: "Kanpur",
      state: "Uttar Pradesh",
      pin: "208002",
    },
  },
  {
    id: "29",
    name: "Rina Das",
    email: "rina.das@gmail.com",
    phone: "+91 9876543490",
    address: {
      location: "T-20, Jadavpur",
      city: "Kolkata",
      state: "West Bengal",
      pin: "700032",
    },
  },
  {
    id: "30",
    name: "Kavita Saini",
    email: "kavita.saini@hotmail.com",
    phone: "+91 9876543500",
    address: {
      location: "G-9, Hawa Sadak",
      city: "Jaipur",
      state: "Rajasthan",
      pin: "302002",
    },
  },
  {
    id: "31",
    name: "Ravindra Tiwari",
    email: "ravindra.tiwari@outlook.com",
    phone: "+91 9876543510",
    address: {
      location: "A-8, Suraj Nagar",
      city: "Raipur",
      state: "Chhattisgarh",
      pin: "492001",
    },
  },
  {
    id: "32",
    name: "Shivani Pandey",
    email: "shivani.pandey@gmail.com",
    phone: "+91 9876543520",
    address: {
      location: "E-16, Saket Nagar",
      city: "Bhopal",
      state: "Madhya Pradesh",
      pin: "462002",
    },
  },
  {
    id: "33",
    name: "Nitin Sharma",
    email: "nitin.sharma@ymail.com",
    phone: "+91 9876543530",
    address: {
      location: "L-10, Kalyan Nagar",
      city: "Gurgaon",
      state: "Haryana",
      pin: "122002",
    },
  },
  {
    id: "34",
    name: "Maya Rao",
    email: "maya.rao@gmail.com",
    phone: "+91 9876543540",
    address: {
      location: "S-12, Banjara Hills",
      city: "Hyderabad",
      state: "Telangana",
      pin: "500034",
    },
  },
  {
    id: "35",
    name: "Dinesh Garg",
    email: "dinesh.garg@outlook.com",
    phone: "+91 9876543550",
    address: {
      location: "J-13, Adarsh Nagar",
      city: "Delhi",
      state: "Delhi",
      pin: "110020",
    },
  },
];

export const vendorsData = [
  {
    name: "Studio A",
    email: "studiosa@example.com",
    phone: "+91 98765 43210",
    address: "123 Main Street, Mumbai, Maharashtra",
    type: "internal",
  },
  {
    name: "Shutter Pro",
    email: "shutterpro@example.com",
    phone: "+91 99887 65432",
    address: "456 Park Road, Delhi, NCR",
    type: "external",
  },
  {
    name: "Perfect Pixels",
    email: "perfectpixels@example.com",
    phone: "+91 99999 12345",
    address: "789 Ocean View, Chennai, Tamil Nadu",
    type: "internal",
  },
  {
    name: "Frame It Studios",
    email: "frameit@example.com",
    phone: "+91 96666 54321",
    address: "101 Sunset Boulevard, Bangalore, Karnataka",
    type: "external",
  },
  {
    name: "Snap Magic",
    email: "snapmagic@example.com",
    phone: "+91 91234 56789",
    address: "202 Galaxy Mall, Kolkata, West Bengal",
    type: "internal",
  },
  {
    name: "Flash Zone",
    email: "flashzone@example.com",
    phone: "+91 90000 12345",
    address: "303 Green Park, Ahmedabad, Gujarat",
    type: "external",
  },
  {
    name: "Picture Perfect",
    email: "pictureperfect@example.com",
    phone: "+91 92111 22334",
    address: "404 Royal Plaza, Pune, Maharashtra",
    type: "internal",
  },
  {
    name: "Lens Factory",
    email: "lensfactory@example.com",
    phone: "+91 95555 66778",
    address: "505 Whitefield Road, Hyderabad, Telangana",
    type: "external",
  },
  {
    name: "Pixel Vault",
    email: "pixelvault@example.com",
    phone: "+91 97000 11223",
    address: "606 MG Road, Jaipur, Rajasthan",
    type: "internal",
  },
  {
    name: "The Shutter Club",
    email: "shutterclub@example.com",
    phone: "+91 94444 33445",
    address: "707 Sector 10, Noida, Uttar Pradesh",
    type: "external",
  },
  {
    name: "Click Master",
    email: "clickmaster@example.com",
    phone: "+91 90222 33344",
    address: "808 Beach Road, Kochi, Kerala",
    type: "internal",
  },
  {
    name: "Pro Pics Studio",
    email: "propics@example.com",
    phone: "+91 93111 22333",
    address: "909 City Center, Surat, Gujarat",
    type: "external",
  },
  {
    name: "Studio Vibe",
    email: "studiovibe@example.com",
    phone: "+91 98333 44556",
    address: "1001 Central Street, Lucknow, Uttar Pradesh",
    type: "internal",
  },
  {
    name: "Snapshot Studio",
    email: "snapshotstudio@example.com",
    phone: "+91 94555 66789",
    address: "1102 Lajpat Nagar, Delhi, NCR",
    type: "external",
  },
  {
    name: "Image Masters",
    email: "imagemasters@example.com",
    phone: "+91 93456 78901",
    address: "1203 Old Town, Bengaluru, Karnataka",
    type: "internal",
  },
  {
    name: "Visionary Studios",
    email: "visionarystudios@example.com",
    phone: "+91 91777 33444",
    address: "1304 High Street, Chandigarh",
    type: "external",
  },
  {
    name: "Timeless Studio",
    email: "timelessstudio@example.com",
    phone: "+91 97555 22334",
    address: "1405 Golden Gate, Mumbai, Maharashtra",
    type: "internal",
  },
  {
    name: "InstaFrames",
    email: "instaframes@example.com",
    phone: "+91 90333 33455",
    address: "1506 Juhu Road, Mumbai, Maharashtra",
    type: "external",
  },
  {
    name: "Artistic Lens",
    email: "artisticlens@example.com",
    phone: "+91 96000 11222",
    address: "1607 Green Park, Delhi, NCR",
    type: "internal",
  },
  {
    name: "Shutter Click",
    email: "shutterclick@example.com",
    phone: "+91 93222 33445",
    address: "1708 Mall Road, Bangalore, Karnataka",
    type: "external",
  },
];
